### PR TITLE
Russian language is done!

### PR DESCRIPTION
**Pull request by guland2000**
Russian language is done! Hope to see it soon in app...
By the way, what is this: reticulating primes... - string 137??????? Aaaaaaa!!!!!! How to translate...

### CODE REVIEW

**Comment by arashpayan** [comment]
Hi @guland2000! Thank you so much for the contribution. I need to get a CLA signing system up and running and then we can merge this in.

As for the meaning of 'Reticulating primes', it doesn't actually mean anything. It's a joke from an old game called Sim City. While the map was generating it would say 'Reticulating splines', which is also meaningless in that context. I replaced 'splines' with 'primes' as a nod to the cryptographic nature of Zood. :smile:

**Comment by guland2000** [comment]
ha ha 😄 😄😄 great joke, i almost broke my brain trying to translate this phrase more time than the main text!!! In short, I will help as much as I can, the project is very interesting!

**Comment by arashpayan** [comment]
Hey @guland2000. I just finished setting up the CLA assistant for the project, which added a comment just above mine with a link to sign. Let me know if you have any trouble with it. :slightly_smiling_face:

**Comment by arashpayan** [comment]
I had to manually bring these changes into master due to a conflict. @guland2000, I've added, changed and removed some strings since you sent this PR, so the Russian needs a little updating (if you have the time+desire).

**Comment by guland2000** [comment]
What i need to do?

**Pull request closed without merging**
